version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt